version: '3'
services:
  proget-web:
    image: inedo/proget:latest
    hostname: proget-web
    restart: always
    environment: 
      - TZ=Asia/Shanghai
    volumes:
      - "proget_extensions:/var/proget/extensions"
      - "proget_packages:/var/proget/packages"
    depends_on:
      - proget-postgres
  proget-postgres:
    image: postgres:9.5
    restart: always
    environment: 
      - TZ=Asia/Shanghai
    volumes:
      - "postgre_volume:/var/lib/postgresql/data"
  proxy:
    image: nginx:1.11
    ports:
      - "801:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - proget-web
volumes:
  proget_extensions:
    external: true
  proget_packages:
    external: true
  postgre_volume:
    external: true