FROM microsoft/dotnet:2.1.2-aspnetcore-runtime

LABEL Name=aspnetcore-debug Version=2.1.2

ENV TZ=Asia/Shanghai

ENV ASPNETCORE_ENVIRONMENT Development

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update \
    && apt-get install -y curl unzip \
    && apt-get install -y procps \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

WORKDIR /app

VOLUME /app